### ISSUE TITLE
Doesn't load banners

### ISSUE THREAD

**Issue by ByteyBeasts** [byrobingames/facebookads#1]
I know you haven't updated this extension for a year, but I still thought it might work. 
When I use Anable Test (in Stencyl's setting) it's working and when I put IDFA on facebook everything seems to work when I test the game. But when I upload on TestFlight with Disabled Test (in Stencyl) it stops to show banners regardless of the settings on Facebook (disabled/enabled testing).

**Comment by byrobingames** [comment]
No is not working, needs to be updated first.
